version: "3.7"


services:
  db:
    image: library/postgres:12
    environment:
      - POSTGRES_DB=house_db
      - POSTGRES_USER=pubg_danaker
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
     - .:/urs/src/house_rest
    environment:
      DJANGO_ADMIN_USERNAME: danaker
      DJANGO_ADMIN_PASSWORD: 1
      DJANGO_SETTINGS_FOLDER: house
    depends_on:
      - db
    env_file:
      - .env

 