version: '3.3'

services:
  db:
    image: library/postgres:12
    environment:
      - POSTGRES_DB=house_db
      - POSTGRES_USER=pubg_danaker
      - POSTGRES_PASSWORD=1
    ports:
      - "5435:5435"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/house
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db